### ISSUE TITLE
Scanning on startup isn't working.

### ISSUE THREAD

**Issue by kevin-mueller** [kevin-mueller/HtmlCssClassCompletion#4]

**Comment by AMUCOMO** [comment]
Updated to 1.1. When I freshly start, VS I still need to click `Tools -> Scan all Projects for css classes` or otherwise I don'r get any suggestions at all for css classes. So if it is intended, that the extension should do it by itself, it is not working like that for me. But that really is a very minor inconvenience.

**Comment by kevin-mueller** [comment]
Yeah the startup issue is really annoying... Sometimes the event is called, sometimes it isn't. Seems to some sort of timing issue. Maybe I'll take another look at it in the future.

**Comment by dev-elena** [comment]
Unfortunately, scanning isn't working either on startup or when I click `Tools -> Scan all Projects for css classes`. 
I'm using VS2022 and am having Blazor app with lots of css files and it would be really appreciated if your extension worked.

**Comment by kevin-mueller** [comment]
@dev-elena Hmm... I'm not sure why the extension doesn't work for you. It seems to work for other people. Could you maybe try creating a new Blazor Project and try it out there? 

Any more info on this would be appreciated.
